Vagrant.configure("2") do |config|
  config.vm.box = 'bento/debian-9.5'
  config.ssh.insert_key = false
  config.vm.hostname = "adguardhome-local"

  config.vm.network :private_network, ip: '192.168.50.102'

  config.vm.provider :virtualbox do |vb|
    vb.name = 'adguardhome-test'
  end

  config.vm.synced_folder "../", "/vagrant/adguard_home", mount_options: ["dmode=775,fmode=664"]
  config.vm.provision "ansible_local" do |ansible|
      ansible.install_mode = "pip"
      ansible.version = "2.5.4"
      ansible.provisioning_path = "/vagrant/adguard_home/tests"
      ansible.playbook = "vagrant.yml"
      ansible.verbose = 'vv'
    end
end
